apiVersion: v1
kind: Service
metadata:
  name: {{ include "routinator.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "routinator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "routinator.selectorLabels" . | nindent 4 }}
  ipFamilyPolicy: PreferDualStack
