apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.qbittorrent.autoscaling.enabled }}
  replicas: {{ .Values.qbittorrent.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.qbittorrent.strategy.type }}
  selector:
    matchLabels:
      {{- include "qbittorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.qbittorrent.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qbittorrent.labels" . | nindent 8 }}
        {{- with .Values.qbittorrent.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.qbittorrent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qbittorrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.qbittorrent.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.qbittorrent.securityContext | nindent 12 }}
          {{- if .Values.qbittorrent.image.sha }}
          image: "{{ .Values.qbittorrent.image.registry }}/{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.qbittorrent.image.sha }}"
          {{- else }}
          image: "{{ .Values.qbittorrent.image.registry }}/{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: torrent-tcp
              containerPort: 50413
              protocol: TCP
            - name: torrent-udp
              containerPort: 50413
              protocol: UDP
          resources:
            {{- toYaml .Values.qbittorrent.resources | nindent 12 }}
          {{- with .Values.qbittorrent.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.qbittorrent.config.persistence.enabled .Values.qbittorrent.volumeMounts }}
          volumeMounts:
          {{- if .Values.qbittorrent.config.persistence.enabled }}
            - name: config
              mountPath: /config
          {{- end }}
          {{- with .Values.qbittorrent.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
        {{- if .Values.qbittorrent.gluetun.enabled }}
        - name: gluten
          securityContext:
            {{- toYaml .Values.qbittorrent.gluetun.securityContext | nindent 12 }}
          {{- if .Values.qbittorrent.gluetun.image.sha }}
          image: "{{ .Values.qbittorrent.gluetun.image.registry }}/{{ .Values.qbittorrent.gluetun.image.repository }}:{{ .Values.qbittorrent.gluetun.image.tag }}@sha256:{{ .Values.qbittorrent.gluetun.image.sha }}"
          {{- else }}
          image: "{{ .Values.qbittorrent.gluetun.image.registry }}/{{ .Values.qbittorrent.gluetun.image.repository }}:{{ .Values.qbittorrent.gluetun.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.qbittorrent.gluetun.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $.Values.qbittorrent.service.web.port }}
              protocol: TCP
            - name: shadowsocks-tcp
              containerPort: 8388
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: 8388
              protocol: UDP
          startupProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
          readinessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
          resources:
            {{- toYaml .Values.qbittorrent.gluetun.resources | nindent 12 }}
          {{- with .Values.qbittorrent.gluetun.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.gluetun.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.qbittorrent.gluetun.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- if or .Values.qbittorrent.config.persistence.enabled .Values.qbittorrent.volumes }}
      volumes:
      {{- if .Values.qbittorrent.config.persistence.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "qbittorrent.configPersistenceName" . }}
      {{- end }}
      {{- with .Values.qbittorrent.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.qbittorrent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.qbittorrent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
