apiVersion: v2
kubeVersion: ">=1.23.0-0"
name: hyperglass
description: hyperglass helm chart for Kubernetes
type: application
version: 3.0.3
# image: ghcr.io/m0nsterrr/hyperglass
appVersion: "v2.0.4"
maintainers:
  - name: Ludovic Ortega
    email: ludovic.ortega@adminafk.fr
sources:
  - https://github.com/M0NsTeRRR/helm-charts/tree/main/charts/hyperglass
home: https://github.com/thatmattlove/hyperglass
icon: https://artifacthub.io/image/e417b561-5fe4-4ee3-9b89-f67df4069169
dependencies:
  - name: valkey
    version: "2.2.*"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: valkey.enabled
